# jfrog cannot support the qps when parallel installation is enabled
[installer]
parallel = false

# for poetry >1.3 - they use a new git lib which does not support the 
# std way of injecting our self-signed CA certs. This flag revert to using
# the old git client.
[experimental]
system-git-client = true

[virtualenvs]
in-project = true
prefer-active-python = true
